## Проекции (Projections)

Чтобы включить понимание для результата, возвращаемого как исключение, фьючерсы также имеют прогнозы. Если исходное 
будущее терпит неудачу, неудачная (`failed`) проекция возвращает будущее, содержащее значение типа `Throwable`. Если 
исходное будущее завершается успешно, неудачная проекция завершается с ошибкой `NoSuchElementException`. Ниже приведен 
пример, который выводит исключение на экран:

```scala
    val f = Future {
      2 / 0
    }
    for (exc <- f.failed) println(exc)
```

Для понимания в этом примере переводится на:

```scala
    f.failed.foreach(exc => println(exc))
```

Поскольку `f` здесь не увенчался успехом, закрытие регистрируется в обратном вызове `foreach` в новом успешном 
`Future[Throwable]`. Следующий пример ничего не выводит на экран:

```scala
    val g = Future {
      4 / 2
    }
    for (exc <- g.failed) println(exc)
```

_Если этот проект окажется полезным тебе - нажми на кнопочку **`★`** в правом верхнем углу._

[<= содержание](https://github.com/steklopod/Parallel-Programming/blob/master/readme.md)
